### ISSUE TITLE
[Bug] wxScrolledWindow import failure from XRC [sf#137]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#217]
**Reported by karlm on 2009-01-23 05:38 UTC**
Hi

When a wxPanel with child widgets is turned into a wxScrolledWindow (using the 'Scrollable' option in the Widget tab), it can be exported to XRC. But that XRC cannot be imported back in to wxGlade.

I am using wxGlade version 0.6.3 on Python 2.5.1 and wxPython 2.8.7.1. SuSe 10.3 if it matters.

The reported error is:
An exception occurred while loading file "None".
This is the error message associated with it:
        CustomWidget instance has no attribute 'set_sizer'
For more details, look at the full traceback on the console.
If you think this is a wxGlade bug, please report it.

Traceback below.

wxg project file attached. 

To generate the error, Load the wxg file, export to XRC, then import the XRC file just generated.

Cheers
Karl
---------------------------
Traceback (most recent call last):
  File "/usr/local/src/wxGlade-0.6.3/main.py", line 665, in _open_app
    p.parse(infile)
  File "/usr/local/src/wxGlade-0.6.3/xml_parse.py", line 280, in parse
    try: XmlWidgetBuilder.parse(self, *args)
  File "/usr/local/src/wxGlade-0.6.3/xml_parse.py", line 70, in parse
    self.parser.parse(source)
  File "/usr/lib64/python2.5/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.5/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.5/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.5/xml/sax/expatreader.py", line 301, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/local/src/wxGlade-0.6.3/xml_parse.py", line 174, in startElement
    XmlWidgetObject(attrs, self)
  File "/usr/local/src/wxGlade-0.6.3/xml_parse.py", line 419, in __init__
    sizeritem, pos)
  File "/usr/local/src/wxGlade-0.6.3/edit_sizers/edit_sizers.py", line 2145, in xml_builder
    parent.set_sizer(sz)
AttributeError: CustomWidget instance has no attribute 'set_sizer'

**Comment by DietmarSchwertberger** [comment]
**Commented by karlm on 2009-01-23 05:38 UTC**
WXG file with  wxScrolledWindow and child widget
Attached file test_scrolled_window.wxg:

    <?xml version="1.0"?>
    
    
    <application path="/home/karlm/src/DArT/ds-7.5/temp/test_scrolled_window.xrc" name="" class="" option="0" language="XRC" top_window="frame_1" encoding="UTF-8" use_gettext="0" overwrite="0" use_new_namespace="0" for_version="2.8" is_template="0">
        <object class="MyFrame" name="frame_1" base="EditFrame">
            <style>wxDEFAULT_FRAME_STYLE</style>
            <title>frame_1</title>
            <object class="wxBoxSizer" name="object_1" base="EditBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                    <flag>wxEXPAND</flag>
                    <border>0</border>
                    <option>1</option>
                    <object class="wxScrolledWindow" name="panel_1" base="EditScrolledWindow">
                        <scroll_rate>10, 10</scroll_rate>
                        <scrollable>1</scrollable>
                        <object class="wxBoxSizer" name="object_2" base="EditBoxSizer">
                            <orient>wxHORIZONTAL</orient>
                            <object class="sizeritem">
                                <flag>wxEXPAND</flag>
                                <border>0</border>
                                <option>1</option>
                                <object class="wxStaticText" name="label_1" base="EditStaticText">
                                    <style>wxALIGN_CENTRE</style>
                                    <attribute>1</attribute>
                                    <label>Test wxScrolledWindow</label>
                                    <size>140, 15</size>
                                </object>
                            </object>
                        </object>
                    </object>
                </object>
            </object>
        </object>
    </application>

**Comment by DietmarSchwertberger** [comment]
**Commented by agriggio on 2009-01-25 09:12 UTC**
Thanks, it should work now (fixed in hg revision 6badf24df629)
