### ISSUE TITLE
[Bug] SAXParseException: not well-formed (invalid token) [sf#146]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#226]
**Reported by martinellison on 2010-06-13 07:10 UTC**
Cannot generate code, get the following traceback:

Traceback (most recent call last):
  File "/usr/share/wxGlade/application.py", line 447, in generate_code
    class_names=class_names)
  File "/usr/share/wxGlade/xml_parse.py", line 527, in __init__
    if from_string: self.parse_string(input)
  File "/usr/share/wxGlade/xml_parse.py", line 74, in parse_string
    self.parser.parse(source)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/expatreader.py", line 220, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/handler.py", line 38, in fatalError
    raise exception
SAXParseException: <unknown>:1:1: not well-formed (invalid token)

Version HG on py 2.6.4 and wxpy 2.8.10.1

**Comment by DietmarSchwertberger** [comment]
**Commented by martinellison on 2010-06-13 07:10 UTC**
wx file occasioning error
Attached file gl2.wxg:

    <?xml version="1.0"?>
    
    
    <application path="" name="" class="" option="0" language="C++" top_window="" encoding="UTF-8" use_gettext="0" overwrite="0" use_new_namespace="1" for_version="2.8" is_template="0" indent_amount="4" indent_symbol="space" source_extension=".cpp" header_extension=".h">
    </application>

**Comment by DietmarSchwertberger** [comment]
**Commented by martinellison on 2010-06-13 08:14 UTC**
Installed Packages
expat.i686                                           2.0.1-10.fc13         

so it might have something to do with the upgrade of expat from 1.05 (?) to 2.0.1

**Comment by DietmarSchwertberger** [comment]
**Commented by agriggio on 2010-06-28 09:16 UTC**
Hello, can you try with the latest version of wxGlade on bitbucket?
(http://bitbucket.org/agriggio/wxglade)
That should work...

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2012-01-07 22:14 UTC**
Close this bug because it works with the current development version.

Thank you for reporting this bug.
Carsten
