### ISSUE TITLE
[Bug] wxGlade doesn't start [sf#158]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#233]
**Reported by nobody on 2013-07-27 02:58 UTC**
I've installed wxPython-src-2.9.4.0.tar.bz2, and wxGlade doesn't start:

~~~~~~~~~~~
$ python bin/wxGlade-0.6.8/wxglade.py 
Starting wxGlade version 0.6.8 on Python 2.7.3
Base directory:             /home/egp/bin/wxGlade-0.6.8
Documentation directory:    /home/egp/bin/wxGlade-0.6.8/docs
Icons directory:            /home/egp/bin/wxGlade-0.6.8/icons
Build-in widgets directory: /home/egp/bin/wxGlade-0.6.8/widgets
Template directory:         /home/egp/bin/wxGlade-0.6.8/templates
Credits file:               /home/egp/bin/wxGlade-0.6.8/credits.txt
License file:               /home/egp/bin/wxGlade-0.6.8/license.txt
Tutorial file:              /home/egp/bin/wxGlade-0.6.8/docs/html/index.html
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/egp/bin/wxGlade-0.6.8/common.py", line 430, in exceptionHandler
    message.error(_('An unexpected error occurs!'))
  File "/home/egp/bin/wxGlade-0.6.8/common.py", line 688, in error
    self.__call__(_("ERROR"), fmt, *args)
  File "/home/egp/bin/wxGlade-0.6.8/common.py", line 651, in __call__
    import misc
  File "/home/egp/bin/wxGlade-0.6.8/misc.py", line 11, in <module>
    import wx
ImportError: No module named wx

Original exception was:
Traceback (most recent call last):
  File "bin/wxGlade-0.6.8/wxglade.py", line 310, in <module>
    run_main()
  File "bin/wxGlade-0.6.8/wxglade.py", line 295, in run_main
    init_stage2(options.start_gui)
  File "bin/wxGlade-0.6.8/wxglade.py", line 252, in init_stage2
    import wxversion
ImportError: No module named wxversion
$ 
~~~~~~~~~~~~~~~~~~

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2013-08-12 05:01 UTC**
Hi Joxy,

It looks like your Python 2.7.3 doesn't find wxPython. Could you execute two Python statements in your Python 2.7.3 environment and add the output to this bug report, please?

The statements are:
import wxversion
import wx

Thanks,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Commented by *anonymous on 2013-08-12 17:08 UTC**
~~~~~~~~~~~
egp@egp1:~$ python
Python 2.7.3 (default, Apr 10 2013, 05:46:21) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wxversion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wxversion
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wx
>>> 
~~~~~~~~~~~~~~~

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2013-08-12 18:25 UTC**
Hi Joxy,

thank you for the details. Your python installation doesn't find the wxPython module. http://wiki.wxpython.org/How%20to%20install%20wxPython provides some hints to install wxPython. Please install the additional package "wxversion" too.

HTH,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Commented by *anonymous on 2013-08-12 19:31 UTC**
Thank you for a link to a thorough guide. I've installed wxpython via aptitude, and Glade now works finely. Thank you, this report can be closed as fixed.

**Comment by DietmarSchwertberger** [comment]
**Updated by cgrohmann on 2013-08-14 04:41 UTC**
- **status**: open --> closed
- **assigned_to**: Carsten Grohmann

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2013-08-14 04:41 UTC**
Hi Joxy,

glad to hear that your problem is fixed and this bug report can be closed.
I've reworked the import to show error messages instead of exception details also.

Regards,
Carsten
