### ISSUE TITLE
[Bug] No_3D attribute for panel or notebook [sf#159]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#234]
**Reported by infocomm on 2013-09-22 06:07 UTC**
I've tried removing the NO_3D attribute from
wxGlade\widgets\panel\panel.py

The same thing happens with notebook.
If I remove the NO_3D I can load a panel, but the notebook, just never shows.

I've tried the standard build but simply can't get it to work any longer.

Is there something I'm doing wrong. 

2013-09-22 15:52:19,700 root ERROR: An unexpected error occurs!
2013-09-22 15:52:19,700 root ERROR: Error type:    <type 'exceptions.AttributeError'>
2013-09-22 15:52:19,701 root ERROR: Error details: 'module' object has no attribute 'NO_3D'
2013-09-22 15:52:19,701 root ERROR: Stack Trace:
2013-09-22 15:52:19,703 root ERROR: Stack Trace:
2013-09-22 15:52:19,706 root ERROR: Traceback (most recent call last):
2013-09-22 15:52:19,706 root ERROR:   File "C:\Program Files\wxGlade\edit_sizers\edit_sizers.py", line 328, in drop_widget
2013-09-22 15:52:19,707 root ERROR:     common.widgets[common.widget_to_add](self.parent, self.sizer, self.pos)
2013-09-22 15:52:19,707 root ERROR:   File "C:\Program Files\wxGlade\widgets\notebook\notebook.py", line 507, in builder
2013-09-22 15:52:19,707 root ERROR:     common.property_panel,
2013-09-22 15:52:19,709 root ERROR:   File "C:\Program Files\wxGlade\widgets\panel\panel.py", line 228, in __init__
2013-09-22 15:52:19,709 root ERROR:     PanelBase.__init__(self, style)
2013-09-22 15:52:19,710 root ERROR:   File "C:\Program Files\wxGlade\widgets\panel\panel.py", line 47, in __init__
2013-09-22 15:52:19,710 root ERROR:     wx.NO_BORDER, wx.NO_3D,
2013-09-22 15:52:19,710 root ERROR: AttributeError: 'module' object has no attribute 'NO_3D'
2013-09-22 15:52:19,710 root ERROR: Local variables of the last stack entry:
2013-09-22 15:52:19,711 root ERROR: style (<type 'int'>): 524288
2013-09-22 15:52:19,711 root ERROR: self (<class 'panel.panel.EditPanel'>): <panel.panel.EditPanel object at 0x03ABE7F0>

Regards
Graeme

**Comment by DietmarSchwertberger** [comment]
**Commented by infocomm on 2013-09-22 14:25 UTC**
Solution Found
==============
It seems wxGlade not compatible with developer version wxPython version 2.9.5.0 only stable release versions wxPython version 2.8.12.1.

Regards

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2013-09-24 20:01 UTC**
Hi Graeme,

the next release will support wx 2.9 / 3.0. Currently the versions 2.6 and 2.8 are supported only.

Thanks to the bug report. I'll check the details and adapt the code.

Regards,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Updated by cgrohmann on 2013-09-24 20:02 UTC**
- **assigned_to**: Carsten Grohmann

**Comment by DietmarSchwertberger** [comment]
**Updated by cgrohmann on 2014-10-12 07:21 UTC**
- **status**: open --> closed

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2014-10-12 07:21 UTC**
Hi Graeme,

in the current development version the wxGlade GUI supports wxPython3 now. Currently the code generators are not aware of wx3. That's the next development step.

Regards,
Carsten
