### ISSUE TITLE
[Bug] Fails to create wxglade directory on first run [sf#164]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#239]
**Reported by godztempus on 2014-11-03 16:32 UTC**
Python 2.7.8
wxGlade v0.7.0
wxPython 3.0.1.1

$ python -c 'import wxglade;wxglade.run_main();'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "wxglade.py", line 323, in run_main
    init_stage1()
  File "wxglade.py", line 188, in init_stage1
    level='INFO',
  File "log.py", line 381, in init
    backupCount=1,
  File "c:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "c:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "c:\Python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\Python27\lib\logging\__init__.py", line 938, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "c:\Python27\lib\codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'C:\\Users\\<user>\\AppData\\Roaming\\wxglade\\wxglade.log'

I have attached a potential fix for the problem. Your call if you want to use it.

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2014-11-07 18:44 UTC**
Hi John,

the bug is fixed in the revision 1584:d12f1c050a77 as well as the next official release.

You can download a patched stable wxGlade version 0.7.0 from https://bitbucket.org/agriggio/wxglade/get/WXG-BRANCH-VERSION_0_7_0.tar.gz.

Thank you for reporting this bug.

Regards,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Updated by cgrohmann on 2014-11-07 18:44 UTC**
- **status**: open --> closed
- **assigned_to**: Carsten Grohmann
