### ISSUE TITLE
[Bug] wxGlade 0.7.0 [sf#171]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#246]
**Reported by teletele on 2015-06-24 18:50 UTC**
1. wxglade directory missing for log file
http://news.gmane.org/gmane.comp.python.wxglade

The same problem, create folders and log file hand, fix problem.
/home/your_user_name/.wxglade/wxglade.log

2. wxGlade 0.7.0 looks on my PCLinuxOS 64bit Mate like someting missing.

From window:
Properties <app>
Option "Top Window" not working, is empty, I can not change.

~~~~~~
$ wxglade
INFO    : Starting wxGlade version not found on Python 2.7.9
INFO    : Current locale settings are:
INFO    :   Language code: en_GB
INFO    :   Encoding: UTF-8
INFO    :   Filesystem encoding: UTF-8
INFO    : Base directory:             /usr/lib/wxGlade
INFO    : Documentation directory:    /usr/lib/wxGlade/docs
INFO    : Icons directory:            /usr/lib/wxGlade/icons
INFO    : Build-in widgets directory: /usr/lib/wxGlade/widgets
INFO    : Template directory:         /usr/lib/wxGlade/templates
INFO    : Credits file:               /usr/lib/wxGlade/credits.txt
INFO    : License file:               /usr/lib/wxGlade/license.txt
INFO    : Tutorial file:              /usr/lib/wxGlade/docs/html/index.html
INFO    : Home directory:             /home/gg
INFO    : Application data directory: /home/gg/.wxglade
INFO    : Configuration file:         /home/gg/.wxglade/wxgladerc
INFO    : History file:               /home/gg/.wxglade/file_history.txt
INFO    : Log file:                   /home/gg/.wxglade/wxglade.log
INFO    : Starting wxGlade version not found on Python 2.7.9
INFO    : Using wxPython 2.8.12.0
INFO    : Found widgets listing -> /usr/lib/wxGlade/widgets/widgets.txt
INFO    : Loading widget modules:
INFO    : Module toggle_button.wconfig not found.
INFO    : Module toggle_button.wconfig not found.
INFO    : Module radio_box.wconfig not found.
INFO    : Module radio_box.wconfig not found.
INFO    : Module choice.wconfig not found.
INFO    : Module choice.wconfig not found.
INFO    : Module grid.wconfig not found.
INFO    : Module grid.wconfig not found.
INFO    : Module custom_widget.wconfig not found.
INFO    : Module custom_widget.wconfig not found.
INFO    : Module menubar.wconfig not found.
INFO    : Module menubar.wconfig not found.
INFO    : Module spacer.wconfig not found.
INFO    : Module spacer.wconfig not found.
INFO    : loaded code generator for XRC
INFO    : loaded code generator for perl
INFO    : loaded code generator for python
INFO    : loaded code generator for C++
INFO    : loaded code generator for lisp
INFO    : Found widgets listing -> /usr/lib/wxGlade/widgets/widgets.txt
INFO    : Loading widget modules:
INFO    : 	frame
INFO    : 	dialog
INFO    : 	panel
INFO    : 	splitter_window
INFO    : 	notebook
INFO    : 	button
INFO    : 	toggle_button
INFO    : 	bitmap_button
INFO    : 	spin_button
INFO    : 	text_ctrl
INFO    : 	spin_ctrl
INFO    : 	slider
INFO    : 	gauge
INFO    : 	static_text
INFO    : 	checkbox
INFO    : 	radio_button
INFO    : 	radio_box
INFO    : 	choice
INFO    : 	combo_box
INFO    : 	list_box
INFO    : 	calendar_ctrl
INFO    : 	datepicker_ctrl
INFO    : 	static_line
INFO    : 	static_bitmap
INFO    : 	list_ctrl
INFO    : 	tree_ctrl
INFO    : 	grid
INFO    : 	custom_widget
INFO    : 	menubar
INFO    : 	statusbar
INFO    : 	toolbar
INFO    : 	spacer
INFO    : 	hyperlink_ctrl
INFO    : Module calendar_ctrl.lisp_codegen not found.
INFO    : Module calendar_ctrl.lisp_codegen not found.
~~~~~~

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-26 19:14 UTC**
Hi,

The first issue (missing .wxglade directory) is well-known and fixed now.

The second one isn't a issue probably: the "Top window" option can only used after a toplevel widget frame, panel, dialog is created.

Try if the option is usable after you've created a toplevel widget, please. Share the log file if not.

Regards,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Commented by teletele on 2015-06-26 21:17 UTC**
Maybe my problem is different.
I use fedora spec (spec for build rpm package) for PCLinuxOS, but with new source code.
Fedora spec don't use " make , makeinstall " but just copy and run files.
So in my case I can just unpack source code and run app.

I download today source code, wxglade 0.7.0 need create folder .wxglade hand 
/home/user_name/.wxglade/
when I just run 
because I have error without folder .wxglade in home directory.:

~~~~~~
$ ./wxglade
Traceback (most recent call last):
  File "./wxglade.py", line 348, in <module>
    run_main()
  File "./wxglade.py", line 323, in run_main
    init_stage1()
  File "./wxglade.py", line 188, in init_stage1
    level='INFO',
  File "/home/gg/src/rpm/SOURCES/wxGlade-0.7.0/log.py", line 381, in init
    backupCount=1,
  File "/usr/lib64/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.7/logging/__init__.py", line 938, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "/usr/lib64/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/home/gg/.wxglade/wxglade.log'
~~~~~~

Maybe is something with source code, I'm not sure,
I tried build from " make , make install " but on PCLinuxOS I see I have many old perl packages and I need rebuild before compile wxglade.
So for now, I let it go / I interrupt work with this.

Which linux do you use ? 
Maybe I see ready package on your linux distro how it looks, works :) ?

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-27 19:08 UTC**
Hi,

I'm on ArchLinux and the wxGlade package contains some additional fixes like shown at https://aur4.archlinux.org/cgit/aur.git/tree/?h=wxglade.

There is an stable branch for wxGlade. That branch bases on wxGlade 0.7.0 and contains some additional fixes e.g. to create the missing .wxglade directory. Maybe you can use that branch to create your package. 

You can download the current stable branch from
https://bitbucket.org/agriggio/wxglade/get/WXG-BRANCH-VERSION_0_7_0.tar.bz2.

HTH,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Commented by teletele on 2015-06-27 19:27 UTC**
But your links not works...
branch removed?

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-27 20:01 UTC**
Try again:
https://bitbucket.org/agriggio/wxglade/get/WXG-BRANCH-VERSION_0_7_0.tar.bz2

**Comment by DietmarSchwertberger** [comment]
**Commented by teletele on 2015-06-28 15:58 UTC**
Now link working, 
missing .wxglade directory fixed in this branch,
but some modules not load, also when I start from python

~~~~
$ python wxglade.py
INFO    : Starting wxGlade version 0.7.0 on Python 2.7.9
INFO    : Current locale settings are:
INFO    :   Language code: en_GB
INFO    :   Encoding: UTF-8
INFO    :   Filesystem encoding: UTF-8
INFO    : Base directory:             /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc
INFO    : Documentation directory:    /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/docs
INFO    : Icons directory:            /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/icons
INFO    : Build-in widgets directory: /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/widgets
INFO    : Template directory:         /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/templates
INFO    : Credits file:               /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/credits.txt
INFO    : License file:               /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/license.txt
INFO    : Tutorial file:              /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/docs/html/index.html
INFO    : Home directory:             /home/gg
INFO    : Application data directory: /home/gg/.wxglade
INFO    : Configuration file:         /home/gg/.wxglade/wxgladerc
INFO    : History file:               /home/gg/.wxglade/file_history.txt
INFO    : Log file:                   /home/gg/.wxglade/wxglade.log
INFO    : Starting wxGlade version 0.7.0 on Python 2.7.9
INFO    : Using wxPython 2.8.12.0
INFO    : Found widgets listing -> /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/widgets/widgets.txt
INFO    : Loading widget modules:
INFO    : Module toggle_button.wconfig not found.
INFO    : Module toggle_button.wconfig not found.
INFO    : Module radio_box.wconfig not found.
INFO    : Module radio_box.wconfig not found.
INFO    : Module choice.wconfig not found.
INFO    : Module choice.wconfig not found.
INFO    : Module grid.wconfig not found.
INFO    : Module grid.wconfig not found.
INFO    : Module custom_widget.wconfig not found.
INFO    : Module custom_widget.wconfig not found.
INFO    : Module menubar.wconfig not found.
INFO    : Module menubar.wconfig not found.
INFO    : Module spacer.wconfig not found.
INFO    : Module spacer.wconfig not found.
INFO    : loaded code generator for XRC
INFO    : loaded code generator for perl
INFO    : loaded code generator for python
INFO    : loaded code generator for C++
INFO    : loaded code generator for lisp
INFO    : Found widgets listing -> /home/gg/Downloads/test/agriggio-wxglade-bc1cdaba4acc/widgets/widgets.txt
INFO    : Loading widget modules:
INFO    : 	frame
INFO    : 	dialog
INFO    : 	panel
INFO    : 	splitter_window
INFO    : 	notebook
INFO    : 	button
INFO    : 	toggle_button
INFO    : 	bitmap_button
INFO    : 	spin_button
INFO    : 	text_ctrl
INFO    : 	spin_ctrl
INFO    : 	slider
INFO    : 	gauge
INFO    : 	static_text
INFO    : 	checkbox
INFO    : 	radio_button
INFO    : 	radio_box
INFO    : 	choice
INFO    : 	combo_box
INFO    : 	list_box
INFO    : 	calendar_ctrl
INFO    : 	datepicker_ctrl
INFO    : 	static_line
INFO    : 	static_bitmap
INFO    : 	list_ctrl
INFO    : 	tree_ctrl
INFO    : 	grid
INFO    : 	custom_widget
INFO    : 	menubar
INFO    : 	statusbar
INFO    : 	toolbar
INFO    : 	spacer
INFO    : 	hyperlink_ctrl
INFO    : Module calendar_ctrl.lisp_codegen not found.
INFO    : Module calendar_ctrl.lisp_codegen not found.
~~~~

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-28 18:26 UTC**
The message of missing modules is not correct at all.
The provided output looks fine and I don't see any errors.

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-28 18:46 UTC**
Are all your questions answered? If yes, I'll close this ticket.

**Comment by DietmarSchwertberger** [comment]
**Commented by teletele on 2015-06-28 19:51 UTC**
~~~~
Licence:
Copyright (c) 2002-2007 Alberto Griggio  
Copyright (c) 2011-2014 Carsten Grohmann 
~~~~
So probably this is your code, and probably you know better.
This ticket can be close,
thanks for help :-)

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2015-06-30 05:18 UTC**
You are welcome

**Comment by DietmarSchwertberger** [comment]
**Updated by cgrohmann on 2015-06-30 05:18 UTC**
- **status**: open --> closed
