### ISSUE TITLE
[Bug] Can't run wxGlade under CentOS 7  [sf#197]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#272]
**Reported by jonas_lindemann on 2016-11-01 14:21 UTC**
Starting wxGlade produces:

~~~
Traceback (most recent call last):
  File "wxglade.py", line 49, in <module>
    import common
  File "/home/....", line 24, in <module>
    import config, compat, plugins
  File "/home/.../compat.py", line 222, in <module>
    wx_ToolTip_SetAutoPop = wx.ToolTip_SetAutoPop
AttributeError: 'module' object has no attribute 'ToolTip_SetAutoPop'
~~~

I semi-fixed this by:

~~~
def dummy(*args): # <---
    pass

if len(wx.VERSION)==5:
    # wxPython Classic
    IS_CLASSIC = True
    IS_PHOENIX = False

    EVT_GRID_CELL_CHANGE = wx.grid.EVT_GRID_CELL_CHANGE
    wx_SystemSettings_GetFont = wx.SystemSettings_GetFont
    wx_SystemSettings_GetColour = wx.SystemSettings_GetColour
    wx_ArtProviderPush = wx.ArtProvider.PushProvider
    wx_ArtProvider_GetBitmap = wx.ArtProvider_GetBitmap
    wx_ToolTip_SetDelay = wx.ToolTip_SetDelay
    wx_ToolTip_SetAutoPop = dummy #<----
    wx_Tree_InsertItemBefore = wx.TreeCtrl.InsertItemBefore
    def SetToolTip(c, s):
        c.SetToolTipString(s)
~~~
        
However, I am not sure this fixes anything. wxGlade seems to crash horrible when closing. We probarbly need some better solution.

-- Jonas

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2016-11-02 20:44 UTC**
Hi Jonas,

it's strange that SetAutoPop is not available on your installation. Replacing it with dummy should be fine, though.

I have only Windows for testing.
Would you mind testing the current version of branch DEV_DS_2016 on your installation and also with Python 3.4 or 3.5 with a recent snapshot of Phoenix?
Does the crash always occur or only when you did load and edit certain files?

Regards,

Dietmar

**Comment by DietmarSchwertberger** [comment]
**Commented by jonas_lindemann on 2016-11-03 09:39 UTC**
On 2016-11-02 21:44, Dietmar Schwertberger wrote:

> Hi Jonas,
>
> it's strange that SetAutoPop is not available on your installation. 
> Replacing it with dummy should be fine, though.
>
Ok.
>
> I have only Windows for testing.
> Would you mind testing the current version of branch DEV_DS_2016 on 
> your installation and also with Python 3.4 or 3.5 with a recent 
> snapshot of Phoenix?
>
I would like to be able to run it without additional installs, but I can 
give it a try.
>
> Does the crash always occur only when you did load and edit certain files?
>
it seems that is was the first time I started it. After restarting it 
most messages went away. The error dialog is a bit annoying. Especially 
if the errors can be ignored.

Otherwise I like wxGlade a lot!

-- Jonas
>
> Regards,
>
> Dietmar
>
> ------------------------------------------------------------------------
>
> *[bugs:#197] <https://sourceforge.net/p/wxglade/bugs/197/> Can't run 
> wxGlade under CentOS 7 *
>
> *Status:* open
> *Created:* Tue Nov 01, 2016 02:21 PM UTC by Jonas Lindemann
> *Last Updated:* Tue Nov 01, 2016 02:21 PM UTC
> *Owner:* nobody
>
> Starting wxGlade produces:
>
> Traceback  (most  recent  call  last):
>    File  "wxglade.py",  line  49,  in  <module>
>      import  common
>    File  "/home/....",  line  24,  in  <module>
>      import  config,  compat,  plugins
>    File  "/home/.../compat.py",  line  222,  in  <module>
>      wx_ToolTip_SetAutoPop  =  wx.ToolTip_SetAutoPop
> AttributeError:  'module'  object  has  no  attribute  'ToolTip_SetAutoPop'
>
> I semi-fixed this by:
>
> def dummy(*args): # <---
>      pass
>
> if len(wx.VERSION)==5:
>      # wxPython Classic
>      IS_CLASSIC = True
>      IS_PHOENIX = False
>
>      EVT_GRID_CELL_CHANGE = wx.grid.EVT_GRID_CELL_CHANGE
>      wx_SystemSettings_GetFont = wx.SystemSettings_GetFont
>      wx_SystemSettings_GetColour = wx.SystemSettings_GetColour
>      wx_ArtProviderPush = wx.ArtProvider.PushProvider
>      wx_ArtProvider_GetBitmap = wx.ArtProvider_GetBitmap
>      wx_ToolTip_SetDelay = wx.ToolTip_SetDelay
>      wx_ToolTip_SetAutoPop = dummy #<----
>      wx_Tree_InsertItemBefore = wx.TreeCtrl.InsertItemBefore
>      def SetToolTip(c, s):
>          c.SetToolTipString(s)
>
> However, I am not sure this fixes anything. wxGlade seems to crash 
> horrible when closing. We probarbly need some better solution.
>
> -- Jonas
>
> ------------------------------------------------------------------------
>
> Sent from sourceforge.net because you indicated interest in 
> https://sourceforge.net/p/wxglade/bugs/197/
>
> To unsubscribe from further messages, please visit 
> https://sourceforge.net/auth/subscriptions/
>


Attached file alternate:

    <html>
      <head>
        <meta content="text/html; charset=windows-1252"
          http-equiv="Content-Type">
      </head>
      <body bgcolor="#FFFFFF" text="#000000">
        <p>On 2016-11-02 21:44, Dietmar Schwertberger wrote:<br>
        </p>
        <blockquote
    cite="mid:%2Fp%2Fwxglade%2Fbugs%2F197%2Fe4eb10e36bbc16bbdddcf9902053034bbfe7afb5.bugs@wxglade.p.sourceforge.net"
          type="cite">
          <div class="markdown_content">
            <p>Hi Jonas,</p>
            <p>it's strange that SetAutoPop is not available on your
              installation. Replacing it with dummy should be fine, though.</p>
          </div>
        </blockquote>
        Ok.<br>
        <blockquote
    cite="mid:%2Fp%2Fwxglade%2Fbugs%2F197%2Fe4eb10e36bbc16bbdddcf9902053034bbfe7afb5.bugs@wxglade.p.sourceforge.net"
          type="cite">
          <div class="markdown_content">
            <p>I have only Windows for testing.<br>
              Would you mind testing the current version of branch
              DEV_DS_2016 on your installation and also with Python 3.4 or
              3.5 with a recent snapshot of Phoenix?<br>
            </p>
          </div>
        </blockquote>
        I would like to be able to run it without additional installs, but I
        can give it a try.<br>
        <blockquote
    cite="mid:%2Fp%2Fwxglade%2Fbugs%2F197%2Fe4eb10e36bbc16bbdddcf9902053034bbfe7afb5.bugs@wxglade.p.sourceforge.net"
          type="cite">
          <div class="markdown_content">
            <p>
              Does the crash always occur only when you did load and edit
              certain files?</p>
          </div>
        </blockquote>
        it seems that is was the first time I started it. After restarting
        it most messages went away. The error dialog is a bit annoying.
        Especially if the errors can be ignored.<br>
        <br>
        Otherwise I like wxGlade a lot!<br>
        <br>
        -- Jonas<br>
        <blockquote
    cite="mid:%2Fp%2Fwxglade%2Fbugs%2F197%2Fe4eb10e36bbc16bbdddcf9902053034bbfe7afb5.bugs@wxglade.p.sourceforge.net"
          type="cite">
          <div class="markdown_content">
            <p>Regards,</p>
            <p>Dietmar</p>
            <hr>
            <p><strong> <a moz-do-not-send="true" class="alink"
                  href="https://sourceforge.net/p/wxglade/bugs/197/">[bugs:#197]</a>
                Can't run wxGlade under CentOS 7 </strong></p>
            <p><strong>Status:</strong> open<br>
              <strong>Created:</strong> Tue Nov 01, 2016 02:21 PM UTC by
              Jonas Lindemann<br>
              <strong>Last Updated:</strong> Tue Nov 01, 2016 02:21 PM UTC<br>
              <strong>Owner:</strong> nobody</p>
            <p>Starting wxGlade produces:</p>
            <div class="codehilite">
              <pre><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
      <span class="n">File</span> <span class="s">"wxglade.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">49</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
        <span class="kn">import</span> <span class="nn">common</span>
      <span class="n">File</span> <span class="s">"/home/...."</span><span class="p">,</span> <span class="n">line</span> <span class="mi">24</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
        <span class="kn">import</span> <span class="nn">config</span><span class="o">,</span> <span class="nn">compat</span><span class="o">,</span> <span class="nn">plugins</span>
      <span class="n">File</span> <span class="s">"/home/.../compat.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">222</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
        <span class="n">wx_ToolTip_SetAutoPop</span> <span class="o">=</span> <span class="n">wx</span><span class="o">.</span><span class="n">ToolTip_SetAutoPop</span>
    <span class="ne">AttributeError</span><span class="p">:</span> <span class="s">'module'</span> <span class="nb">object</span> <span class="n">has</span> <span class="n">no</span> <span class="n">attribute</span> <span class="s">'ToolTip_SetAutoPop'</span>
    </pre>
            </div>
            <p>I semi-fixed this by:</p>
            <div class="codehilite">
              <pre>def dummy(*args): # &lt;---
        pass
    
    if len(wx.VERSION)==5:
        # wxPython Classic
        IS_CLASSIC = True
        IS_PHOENIX = False
    
        EVT_GRID_CELL_CHANGE = wx.grid.EVT_GRID_CELL_CHANGE
        wx_SystemSettings_GetFont = wx.SystemSettings_GetFont
        wx_SystemSettings_GetColour = wx.SystemSettings_GetColour
        wx_ArtProviderPush = wx.ArtProvider.PushProvider
        wx_ArtProvider_GetBitmap = wx.ArtProvider_GetBitmap
        wx_ToolTip_SetDelay = wx.ToolTip_SetDelay
        wx_ToolTip_SetAutoPop = dummy #&lt;----
        wx_Tree_InsertItemBefore = wx.TreeCtrl.InsertItemBefore
        def SetToolTip(c, s):
            c.SetToolTipString(s)
    </pre>
            </div>
            <p>However, I am not sure this fixes anything. wxGlade seems to
              crash horrible when closing. We probarbly need some better
              solution.</p>
            <p>-- Jonas</p>
            <hr>
            <p>Sent from sourceforge.net because you indicated interest in <a
                moz-do-not-send="true"
                href="https://sourceforge.net/p/wxglade/bugs/197/">https://sourceforge.net/p/wxglade/bugs/197/</a></p>
            <p>To unsubscribe from further messages, please visit <a
                moz-do-not-send="true"
                href="https://sourceforge.net/auth/subscriptions/">https://sourceforge.net/auth/subscriptions/</a></p>
          </div>
          <div itemscope="" itemtype="http://schema.org/EmailMessage">
            <div itemprop="action" itemscope=""
              itemtype="http://schema.org/ViewAction">
              <link itemprop="url"
                href="https://sourceforge.net/p/wxglade/bugs/197/">
              <meta itemprop="name" content="View">
            </div>
            <meta itemprop="description" content="View">
          </div>
        </blockquote>
        <br>
      </body>
    </html>

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2016-11-03 20:44 UTC**
> I would like to be able to run it without additional installs, but I can
> give it a try.
If it runs, then it's fine to stay with 2.7 for a while. In case of hard C++ crashes, it's interesting to see the differences to find a workaround, but it's quite some time that I had one...
I've just updated the DEV_DS_2016 branch with a major functional upgrade.


> it seems that is was the first time I started it. After restarting it
> most messages went away. The error dialog is a bit annoying. Especially
> if the errors can be ignored.
I don't like the current logging system either. Usually, I'm fine with printing warnings on the console and a simple backtrace in case of something major...

Regards,

Dietmar

**Comment by DietmarSchwertberger** [comment]
**Commented by cgrohmann on 2016-11-04 20:31 UTC**
Hi Jonas,

I've implemented the current bug report dialog to simplify the reporting the bugs.

The dialog should raised for major errors only. The dialog should **never** raised if the error can be ignored. That would be a fail and will be fixed.

Please report errors told by the dialog. You can open a ticket, send a mail to the mailing list or to me directly. 

Regards,
Carsten

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-02-14 21:52 UTC**
- **status**: open --> closed
- **assigned_to**: Dietmar Schwertberger

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-02-14 21:52 UTC**
I just tried with a Phoenix snapshot and Python 3.5.
Startup seems to work.
For Classic, I've added your workaround.
