### ISSUE TITLE
[Bug] `Dialog_with_two_buttons` template has malformed dialog size [sf#214]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#288]
**Reported by brendansimon on 2017-07-17 13:55 UTC**
I created a new project from `File => New from Template... => Dialog_with_two_buttons`.

The generated code does not run.

~~~
test.py:31: wxPyDeprecationWarning: Call to deprecated item. Use DLG_UNIT instead.
  self.SetSize(wx.DLG_SZE(self, (200, 150)))
Traceback (most recent call last):
  File "yyy.py", line 49, in OnInit
    self.dialog_1 = MyDialog(None, wx.ID_ANY, "")
  File "yyy.py", line 24, in __init__
    self.__set_properties()
  File "yyy.py", line 31, in __set_properties
    self.SetSize(wx.DLG_SZE(self, (200, 150)))
TypeError: Window.SetSize(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'Point'
  overload 2: argument 1 has unexpected type 'Point'
  overload 3: argument 1 has unexpected type 'Point'
  overload 4: argument 1 has unexpected type 'Point'
OnInit returned false, exiting...
~~~

The dialog `size` property is set to `200, 150d`.  Not sure what the `d` is but removing it and regenerating seems to produce different code that does run correctly :)

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-07-17 15:47 UTC**
"d" means to use so called Dialog units, which is a way to scale depending on the font size.
I also was not aware of this feature and also the unit test cases did not test this feature...

The signature of DLG_SIZE / DLG_UNIT changed with Phoenix (https://github.com/wxWidgets/Phoenix/issues/426)
I did implement a fix already to explicitely call wx.Size for the argument to the function, but did not upload the commits before. I have done so now.

Please check whether everything is working.
The commits includes some major refactoring of the code generation. This is the basis for new features like GridBagSizers. Expect some problems...

Regards,
Dietmar

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-07-17 15:48 UTC**
- **status**: open --> pending
- **assigned_to**: Dietmar Schwertberger

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-07-30 09:10 UTC**
- **status**: pending --> closed
